### ISSUE TITLE
WARNING: A restricted method in java.lang.System has been called (JDK24)

### ISSUE THREAD

**Issue by khmarbaise** [jline/jline3#1067] opened 2024-09-07 11:57 UTC
Currently the jline-3.26.3 is used in Maven Core which produces a WARNING like this:
```
$> mvn clean verify 
WARNING: A restricted method in java.lang.System has been called
WARNING: java.lang.System::load has been called by org.jline.nativ.JLineNativeLoader in an unnamed module (file:/Users/khm/tools/maven/lib/jline-3.26.3.jar)
WARNING: Use --enable-native-access=ALL-UNNAMED to avoid a warning for callers in this module
WARNING: Restricted methods will be blocked in a future release unless native access is enabled
```
This warning is issued while running under JDK24.ea.13

**Comment by gnodet** [comment] 2024-09-07 13:45
Which version of maven ?

**Comment by khmarbaise** [comment] 2024-09-08 09:53
I have tested with Maven 4.0.0-beta-4, 4.0.0-beta-3, 3.9.X(all versions), 3.8.X(all versions)... A simply `mvn --version` also triggers the warning:
```
mvn --version
$> mvn --version
WARNING: A restricted method in java.lang.System has been called
WARNING: java.lang.System::load has been called by org.fusesource.jansi.internal.JansiLoader in an unnamed module (file:/Users/khm/tools/maven/lib/jansi-2.4.1.jar)
WARNING: Use --enable-native-access=ALL-UNNAMED to avoid a warning for callers in this module
WARNING: Restricted methods will be blocked in a future release unless native access is enabled

Apache Maven 3.9.8 (36645f6c9b5079805ea5009217e36f2cffd34256)
Maven home: /Users/khm/tools/maven
Java version: 24-ea, vendor: Oracle Corporation, runtime: /Users/khm/.sdkman/candidates/java/24.ea.13-open
Default locale: en_DE, platform encoding: UTF-8
OS name: "mac os x", version: "14.6.1", arch: "aarch64", family: "mac"
```

**Comment by gnodet** [comment] 2024-09-08 11:15
We need to add argument that to the startup scripts.

**Comment by khmarbaise** [comment] 2024-09-08 12:31
Wouldn't it be better to go the way that jline detects which JDK it is running under automatically for example via a multi-release jar which handles that ... using FFM (JDK22+) ? (Just an idea... not familiar with the JLine code)...

**Comment by gnodet** [comment] 2024-09-08 13:48
I think JLine almost always needs native access, either because of the FFM provider or because it will need to load a native library.
Only the exec provider can work without native, but it's only supported on Unix systems.

**Comment by slachiewicz** [comment] 2024-09-10 22:09
Also with other projects, our default validation fails.

[INFO] --- enforcer:3.5.0:enforce (enforce-bytecode-version) @ maven-filtering ---
[INFO] Restricted to JDK 17 yet org.jline:jline:jar:3.26.3:test contains org/jline/terminal/impl/ffm/CLibrary$termios.class targeted to JDK 22

Error:  Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:3.5.0:enforce (enforce-bytecode-version) on project maven-filtering: 
Error:  Rule 0: org.codehaus.mojo.extraenforcer.dependencies.EnforceBytecodeVersion failed with message:
Error:  Found Banned Dependency: org.jline:jline:jar:3.26.3
Error:  Use 'mvn dependency:tree' to locate the source of the banned dependencies.

**Comment by gnodet** [comment] 2024-09-11 08:52
> Also with other projects, our default validation fails.
> 
> [INFO] --- enforcer:3.5.0:enforce (enforce-bytecode-version) @ maven-filtering --- [INFO] Restricted to JDK 17 yet org.jline:jline:jar:3.26.3:test contains org/jline/terminal/impl/ffm/CLibrary$termios.class targeted to JDK 22
> 
> Error: Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:3.5.0:enforce (enforce-bytecode-version) on project maven-filtering: Error: Rule 0: org.codehaus.mojo.extraenforcer.dependencies.EnforceBytecodeVersion failed with message: Error: Found Banned Dependency: org.jline:jline:jar:3.26.3 Error: Use 'mvn dependency:tree' to locate the source of the banned dependencies.

That's unrelated and I think the detection is too strict.  In this case, the JLine FFM provider requires JDK 22, but those classes are optional.  Maven can be switched to using individual JLine jars if needed, that may help.

**Comment by gnodet** [comment] 2024-09-11 09:10
> I have tested with Maven 4.0.0-beta-4, 4.0.0-beta-3, 3.9.X(all versions), 3.8.X(all versions)... A simple `mvn --version` also triggers the warning:
> 
> ```
> mvn --version
> $> mvn --version
> WARNING: A restricted method in java.lang.System has been called
> WARNING: java.lang.System::load has been called by org.fusesource.jansi.internal.JansiLoader in an unnamed module (file:/Users/khm/tools/maven/lib/jansi-2.4.1.jar)
> WARNING: Use --enable-native-access=ALL-UNNAMED to avoid a warning for callers in this module
> WARNING: Restricted methods will be blocked in a future release unless native access is enabled
> 
> Apache Maven 3.9.8 (36645f6c9b5079805ea5009217e36f2cffd34256)
> Maven home: /Users/khm/tools/maven
> Java version: 24-ea, vendor: Oracle Corporation, runtime: /Users/khm/.sdkman/candidates/java/24.ea.13-open
> Default locale: en_DE, platform encoding: UTF-8
> OS name: "mac os x", version: "14.6.1", arch: "aarch64", family: "mac"
> ```
> 
> The README tells already something like this:
> 
> > With JLine 3.26, the FFM provider requires JDK 22 with the --enable-native-access=ALL-UNNAMED JVM option.
> 
> If I correctly understand the warning which is related to the usage of this methods: https://download.java.net/java/early_access/jdk24/docs/api/restricted-list.html

I've raised https://github.com/apache/maven/pull/1718

**Comment by gnodet** [comment] 2024-09-11 09:31
> Also with other projects, our default validation fails.
> 
> [INFO] --- enforcer:3.5.0:enforce (enforce-bytecode-version) @ maven-filtering --- [INFO] Restricted to JDK 17 yet org.jline:jline:jar:3.26.3:test contains org/jline/terminal/impl/ffm/CLibrary$termios.class targeted to JDK 22
> 
> Error: Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:3.5.0:enforce (enforce-bytecode-version) on project maven-filtering: Error: Rule 0: org.codehaus.mojo.extraenforcer.dependencies.EnforceBytecodeVersion failed with message: Error: Found Banned Dependency: org.jline:jline:jar:3.26.3 Error: Use 'mvn dependency:tree' to locate the source of the banned dependencies.

Raised https://github.com/apache/maven/pull/1719

**Comment by gnodet** [comment] 2024-09-11 09:32
Closing this one as there's not much JLine can do for the JDK24 warning and for the enforcer, we need to use individual jars.

**Closed** 2024-09-11 10:46 UTC

**Comment by nipafx** [comment] 2025-01-05 11:24
I just stumbled across that JDK warning and the search led me here. Great to see the community noticing and reacting to these changes quickly. 😃👍🏾

I think everybody in this thread is aware, but just in case: On JDK 22 and 23, this message was an error that was triggered by FFM. On 24, it was temporarily downgraded to a warning, so JNI could be onboarded. Specifically, [this is the list of _restricted methods_](https://download.java.net/java/early_access/jdk24/docs/api/restricted-list.html) that trigger the message (once JDK 24 is GA, that link breaks and [the list should be here](https://docs.oracle.com/en/java/javase/24/docs/api/restricted-list.html)). In some future release, this warning will become an error again (this time including JNI).

To make all this easier to understand for the user, I recommend to place calls to restricted methods in a `try`-block, where `catch` prints/logs a message that explains what's going on and what the solution is (~> `--enable-native-access`) and then rethrows.

Speaking of `--enable-native-access`, I saw that the README recommends `--enable-native-access=ALL-UNNAMED`. While this works, it unlocks native access for _all_ code on the class path - something I wouldn't feel comfortable recommending to (my) users as the only option. Since JANSI does come [with a module name](https://github.com/fusesource/jansi/blob/master/pom.xml#L210), why not mention `--enable-native-access=org.fusesource.jansi` as well?

If there's interest in these changes, I can open a PR.

**Comment by norrisjeremy** [comment] 2025-01-10 20:23
> I just stumbled across that JDK warning and the search led me here. Great to see the community noticing and reacting to these changes quickly. 😃👍🏾
> 
> I think everybody in this thread is aware, but just in case: On JDK 22 and 23, this message was an error that was triggered by FFM. On 24, it was temporarily downgraded to a warning, so JNI could be onboarded. Specifically, [this is the list of _restricted methods_](https://download.java.net/java/early_access/jdk24/docs/api/restricted-list.html) that trigger the message (once JDK 24 is GA, that link breaks and [the list should be here](https://docs.oracle.com/en/java/javase/24/docs/api/restricted-list.html)). In some future release, this warning will become an error again (this time including JNI).
> 
> To make all this easier to understand for the user, I recommend to place calls to restricted methods in a `try`-block, where `catch` prints/logs a message that explains what's going on and what the solution is (~> `--enable-native-access`) and then rethrows.
> 
> Speaking of `--enable-native-access`, I saw that the README recommends `--enable-native-access=ALL-UNNAMED`. While this works, it unlocks native access for _all_ code on the class path - something I wouldn't feel comfortable recommending to (my) users as the only option. Since JANSI does come [with a module name](https://github.com/fusesource/jansi/blob/master/pom.xml#L210), why not mention `--enable-native-access=org.fusesource.jansi` as well?
> 
> If there's interest in these changes, I can open a PR.

Won't that only work if the offending library is loaded from the module-path?
And thus wouldn't work in this case since the offending library is loaded by Maven on the class-path?

**Comment by norrisjeremy** [comment] 2025-01-10 20:24
> > I just stumbled across that JDK warning and the search led me here. Great to see the community noticing and reacting to these changes quickly. 😃👍🏾
> > I think everybody in this thread is aware, but just in case: On JDK 22 and 23, this message was an error that was triggered by FFM. On 24, it was temporarily downgraded to a warning, so JNI could be onboarded. Specifically, [this is the list of _restricted methods_](https://download.java.net/java/early_access/jdk24/docs/api/restricted-list.html) that trigger the message (once JDK 24 is GA, that link breaks and [the list should be here](https://docs.oracle.com/en/java/javase/24/docs/api/restricted-list.html)). In some future release, this warning will become an error again (this time including JNI).
> > To make all this easier to understand for the user, I recommend to place calls to restricted methods in a `try`-block, where `catch` prints/logs a message that explains what's going on and what the solution is (~> `--enable-native-access`) and then rethrows.
> > Speaking of `--enable-native-access`, I saw that the README recommends `--enable-native-access=ALL-UNNAMED`. While this works, it unlocks native access for _all_ code on the class path - something I wouldn't feel comfortable recommending to (my) users as the only option. Since JANSI does come [with a module name](https://github.com/fusesource/jansi/blob/master/pom.xml#L210), why not mention `--enable-native-access=org.fusesource.jansi` as well?
> > If there's interest in these changes, I can open a PR.
> 
> Won't that only work if the offending library is loaded from the module-path? And thus wouldn't work in this case since the offending library is loaded by Maven on the class-path?

Apologies, disregard, I misread this from the wrong project.

**Comment by bitspittle** [comment] 2025-08-02 16:54
Since this was closed as not planned, I'm looking for guidance....

I'm writing a Kotlin library which itself depends on jline3, and now users of my library are getting the warning when compiling with JDK24. 

After some initial research, I was planning on telling them to add the following JVM args: `-XX:+IgnoreUnrecognizedVMOptions --enable-native-access=ALL-UNNAMED`, but it's not clear to me yet if this is actually right, or a temporary solution. Some posts I've read make me think this will break in near future JDKs but it's not clear to me.

Is there advice for what a library author wrapping jline3 should ideally be doing? In order to make removing the warning both as painless for end users as possible AND being future proof? (I'd be much more comfortable telling them to add a line like `--enable-native-access=jansi` than `ALL-UNNAMED`, for example)

**Comment by gnodet** [comment] 2025-08-05 16:21
> Since this was closed as not planned, I'm looking for guidance....
>
> I'm writing a Kotlin library which itself depends on jline3, and now users of my library are getting the warning when compiling with JDK24.
> 
> After some initial research, I was planning on telling them to add the following JVM args: `-XX:+IgnoreUnrecognizedVMOptions --enable-native-access=ALL-UNNAMED`, but it's not clear to me yet if this is actually right, or a temporary solution. Some posts I've read make me think this will break in near future JDKs but it's not clear to me.
> 
> Is there advice for what a library author wrapping jline3 should ideally be doing? In order to make removing the warning both as painless for end users as possible AND being future proof? (I'd be much more comfortable telling them to add a line like `--enable-native-access=jansi` than `ALL-UNNAMED`, for example)

It has been closed as not planned because there's not much JLine can really do at this point. The burden goes to the project using JLine: you need to specify the correct javac arguments to enable native access without a warning.
The problem is that being able to have a `--enable-native-access` argument without a `ALL-UNNAMED` requires JLine to define proper JPMS modules.  This is on my TODO list, but is not a trivial task.

If you really want to avoid this warning, use the small jars instead of the `jline` one and don't depend on `jline-terminal-ffm`.

**Comment by bitspittle** [comment] 2025-08-05 17:32
I'm currently using "jline-terminal" and "jline-terminal-ansi" as my only dependencies. Is that what you mean by small jars?

> The burden goes to the project using JLine: you need to specify the correct javac arguments to enable native access without a warning.

At the moment, my understanding is the only thing I can do for now is, as an intermediate library author that wraps jline, add docs to my README telling users to add the following code to their Gradle build script:

```diff
application {
+   applicationDefaultJvmArgs = listOf(
+      "-XX:+IgnoreUnrecognizedVMOptions", // Optional: But lets you build with older JDKs
+       "--enable-native-access=ALL-UNNAMED",
+   )
    mainClass.set("MainKt")
}
```

**Comment by gnodet** [comment] 2025-08-05 17:40
> I'm currently using "jline-terminal" and "jline-terminal-ansi" as my only dependencies. Is that what you mean by small jars?

Yes, I missed the fact that `jline-terminal-jansi` requires the flag too.  You could use the `exec` provider which does not require any native access, but that won't work on windows.

> > The burden goes to the project using JLine: you need to specify the correct javac arguments to enable native access without a warning.
> 
> At the moment, my understanding is the only thing I can do for now is, as an intermediate library author that wraps jline, add docs to my README telling users to add the following code to their Gradle build script:
> 
> application {
> +   applicationDefaultJvmArgs = listOf(
> +      "-XX:+IgnoreUnrecognizedVMOptions", // Optional: But lets you build with older JDKs
> +       "--enable-native-access=ALL-UNNAMED",
> +   )
>     mainClass.set("MainKt")
> }

Yes, unfortunately.
I'll try to see if adding better JPMS support is feasible...

**Comment by gnodet** [comment] 2025-08-05 22:52
Could be fixed with #1374  ...

**Comment by mateusfccp** [comment] 2025-11-25 19:02
I have this warning, but after using the mentioned flag my terminal size becomes always 0x0. I don't know what is the relation between native access an the terminal size, but it is blocking me.

**Comment by hellohi63636hu-dotcom** [comment] 2026-09-06 12:03
### ****
