### ISSUE TITLE
Problem with command prompt

### ISSUE THREAD

**Issue by AgentLV** [jline/jline3#53] opened 2016-12-04 21:22 UTC
I'm currently trying to update from jLine2 to jLine3 but I'm having problems creating a command prompt which always "stays as the bottom". This is want I'm currently testing with. 
```
public class Main {

    public static void main( String[] args ) {
        new Main();
    }

    private Terminal terminal;
    private LineReader reader;

    private Main() {
        try {
            this.terminal = TerminalBuilder.terminal();
            this.reader = LineReaderBuilder.builder().terminal( terminal ).build();

            Thread thread = new Thread( new Runnable() {
                @Override
                public void run() {
                    while ( !Thread.interrupted() ) {
                        try {
                            Thread.sleep( 1000 );
                        } catch ( InterruptedException e ) {
                            break;
                        }

                        terminal.writer().println( "test" );
                        terminal.flush();
                    }
                }
            } );
            thread.start();

            String line;
            while ( !Thread.interrupted() ) {
                line = reader.readLine( "> " );

                if ( line == null ) {
                    continue;
                }

                if ( line.equalsIgnoreCase( "quit" ) ) {
                    thread.interrupt();
                    System.exit( 0 );
                    break;
                }
            }
        } catch ( IOException e ) {
            e.printStackTrace();
        }
    }

}
```
Link to google group topic https://groups.google.com/forum/#!topic/jline-users/VBLZ6Wn15LY

**Comment by gnodet** [comment] 2016-12-04 21:49
I see a similar behavior between recent jline2 released and jline3 releaes, and I'm not sure to understand what behavior you expect from this program...
If you want to force a redraw of the line, change the call to `terminal.flush()` with the following lines:
```
                    ((LineReaderImpl) reader).redrawLine();
                    ((LineReaderImpl) reader).redisplay();
```

**Comment by AgentLV** [comment] 2016-12-04 22:08
`public class Main {

    public static void main( String[] args ) {
        new Main();
    }

    private Terminal terminal;
    private LineReader reader;

    private Main() {
        try {
            this.terminal = TerminalBuilder.terminal();
            this.reader = LineReaderBuilder.builder().terminal( terminal ).build();

            Thread thread = new Thread( new Runnable() {
                @Override
                public void run() {
                    while ( !Thread.interrupted() ) {
                        try {
                            Thread.sleep( 1000 );
                        } catch ( InterruptedException e ) {
                            break;
                        }

                        terminal.writer().println( "test" );
                        ((LineReaderImpl) reader).redrawLine();
                        ((LineReaderImpl) reader).redisplay();
                    }
                }
            } );
            thread.start();

            String line;
            while ( !Thread.interrupted() ) {
                line = reader.readLine( "> " );

                if ( line == null ) {
                    continue;
                }

                if ( line.equalsIgnoreCase( "quit" ) ) {
                    thread.interrupt();
                    System.exit( 0 );
                    break;
                }
            }
        } catch ( IOException e ) {
            e.printStackTrace();
        }
    }

}`

Then this occurs https://abload.de/img/ezgif.com-video-to-gicxsea.gif

**Comment by gnodet** [comment] 2016-12-04 22:22
Well, yes, it redraws the prompt at the bottom, isn't that what you want ?

**Comment by gnodet** [comment] 2016-12-04 22:34
The two lines can be replaced now with the following ones, using public apis:
```
                    reader.callWidget( LineReader.REDRAW_LINE );
                    reader.callWidget( LineReader.REDISPLAY );
```

**Comment by AgentLV** [comment] 2016-12-04 22:37
Yeah the prompt staying at the bottom is working well, but I don't want the text appending in the output.

**Comment by gnodet** [comment] 2016-12-04 23:10
Which text ?

**Comment by gnodet** [comment] 2016-12-04 23:29
I'm really failing to understand why you want to allow some code to write to the terminal, but hide it at the same time ;-)
If you want the "test" strings to not appear on the terminal, the best way is to change the stream.  If some part of your application uses `System.out` or `System.err`, those streams can be changed to something else if you want using `System.setOut` or `System.setErr`.
If you don't have any control over the printing of those "test" strings, I'm not sure when you want to redraw the code.  The `LineReader` will only react to the input stream, so if there's no key typed, the output will never be updated.

**Comment by AgentLV** [comment] 2016-12-04 23:54
Sorry for the confusion :/
In my code when thread keeps printing "test", I did this to kind of simulate some output. However what bugs me is that as soon as I type something in the command prompt/line it is inserted in front of the test string and displayed in the terminal and I also don't know why. This gif shows the problem https://abload.de/img/ezgif.com-video-to-gicxsea.gif
Hope my problem is clearer now.

**Comment by gnodet** [comment] 2016-12-05 07:09
Not yet, sorry ;-)
I understand that "test" is just a simulation, but in reality, what do you see ?  Is that some logging statements, some weird characters, random letters  ? Can you grab a screenshot / video or your real screen ?

**Comment by gnodet** [comment] 2016-12-05 07:13
For example, try the following in your favorite unix shell:
```
> (for i in a b c d e f g h i j k l m n o p q r s t u v w x y z; do sleep 1 ; echo $i ; done) &
```
I doubt the output will really be clean.

**Comment by AgentLV** [comment] 2016-12-05 15:47
https://abload.de/img/ezgif.com-video-to-gicxsea.gif this gif shows the problem, i am typing something into the command prompt and its being prepended to the output, but I don't know why. E.g. test keeps being printed to the terminal every second, but when I write "123" into the command prompt, "123test" is being printed to the terminal, which is really strange.

**Comment by gnodet** [comment] 2016-12-05 15:59
Yeah, I understand the problem, but I don't think JLine can do anything here.  You should not allow your app to write to the terminal at the same time.  Again, if your app is using System.out / System.err, you can override those streams to provide custom streams that would redirect to something else to not pollute your terminal.
Is that a problem ?

**Comment by AgentLV** [comment] 2016-12-05 17:30
Could you give me an example? I'm struggling to find a solution.

**Comment by gnodet** [comment] 2016-12-05 18:39
I can't until you tell me what is written and where does it come from...

**Comment by AgentLV** [comment] 2016-12-05 19:46
Still testing with this small program `public class Main {

    public static void main( String[] args ) {
        new Main();
    }

    private Terminal terminal;
    private LineReader reader;

    private Main() {
        try {
            this.terminal = TerminalBuilder.terminal();
            this.reader = LineReaderBuilder.builder().terminal( terminal ).build();

            Thread thread = new Thread( new Runnable() {
                @Override
                public void run() {
                    while ( !Thread.interrupted() ) {
                        try {
                            Thread.sleep( 1000 );
                        } catch ( InterruptedException e ) {
                            break;
                        }

                        terminal.writer().println( "test" );
                        terminal.flush();
                    }
                }
            } );
            thread.start();

            String line;
            while ( !Thread.interrupted() ) {
                line = reader.readLine( "> " );

                if ( line == null ) {
                    continue;
                }

                if ( line.equalsIgnoreCase( "quit" ) ) {
                    thread.interrupt();
                    System.exit( 0 );
                    break;
                }
            }
        } catch ( IOException e ) {
            e.printStackTrace();
        }
    }

}`

**Comment by gnodet** [comment] 2016-12-13 08:22
I'm closing this issue now.  Please reopen if you want to provide more information, but JLine is not responsible for other threads printing to the terminal...

**Closed by gnodet** 2016-12-13 08:22 UTC
Labels: question

**Comment by gnodet** [comment] 2016-12-21 11:12
Note that this is also somewhat similar to the [demo](https://github.com/jline/jline3/wiki/Demo%20Widgets%20and%20Keymaps) I create recently.

**Comment by jmcclell** [comment] 2017-10-07 20:42
@gnodet I actually have the same issue as @AgentLV. Perhaps my use-case will make more clear what the problem is.
In my case, I am writing a CLI-based chat application. Think of how chat UIs work: there's a constant place to type at the bottom, and a flowing stream of incoming chat lines above it. This is the type of UI I'm trying to create on the CLI with Jline. I am using Jline to do all the writing to the console, but when I want to output a new chat message to the screen, I want it to appear before the input prompt. Unfortunately, the current value of the input prompt is continually pre-pended to the new chat line, as we can see in the animation that @AgentLV provided.

Do you have any hints or tips with this in mind and knowing that Jline is used for all input/output?
