### ISSUE TITLE
mvn install fails ExternalTerminalTest

### ISSUE THREAD

**Issue by musclewizard** [jline/jline3#429] opened 2019-08-20 18:33 UTC
[INFO] Running org.jline.terminal.impl.ExternalTerminalTest
[ERROR] Tests run: 6, Failures: 0, Errors: 3, Skipped: 1, Time elapsed: 1.185 s <<< FAILURE! - in org.jline.terminal.impl.ExternalTerminalTest
[ERROR] testReadUntilEof(org.jline.terminal.impl.ExternalTerminalTest)  Time elapsed: 0.037 s  <<< ERROR!
java.lang.NumberFormatException: For input string: ""
	at org.jline.terminal.impl.ExternalTerminalTest.testReadUntilEof(ExternalTerminalTest.java:204)

[ERROR] testExceptionOnInputStream(org.jline.terminal.impl.ExternalTerminalTest)  Time elapsed: 0.007 s  <<< ERROR!
java.lang.NumberFormatException: For input string: ""
	at org.jline.terminal.impl.ExternalTerminalTest.testExceptionOnInputStream(ExternalTerminalTest.java:186)

[ERROR] testPaused(org.jline.terminal.impl.ExternalTerminalTest)  Time elapsed: 0.008 s  <<< ERROR!
java.lang.NumberFormatException: For input string: ""
	at org.jline.terminal.impl.ExternalTerminalTest.testPaused(ExternalTerminalTest.java:145)

**Comment by musclewizard** [comment] 2019-08-20 18:38
It fails when running from the terminal rxvt-unicode (v9.22), but passes when running from another terminal. Let me know if I can provide further info.

**Comment by gnodet** [comment] 2020-01-07 09:26
Can't reproduce the problem on rxvt-unicode (v9.22) on Fedora 30.  Closing for now, please reopen if needed.

**Closed by gnodet** 2020-01-07 09:26 UTC
