### ISSUE TITLE
Pressing tab during i-search doubles text on input buffer

### ISSUE THREAD

**Issue by bdw429s** [jline/jline3#250] opened 2018-04-04 00:36 UTC
I'm not sure what the expected behavior is here.  If I type Ctrl-R and start searching through my history and what I'm typing is matching an item in my history, then pressing tab seems to fire my completor (which finishes the word) but the match from the history is also added to the buffer as well.  

Below is what happens when I search for the word `history` in my history buffer.  Note, `history` is also a CommandBox command so my completor will finish the word on tab.

![image](https://user-images.githubusercontent.com/584009/38282541-45a29806-3776-11e8-95c3-5b5f9dd90577.png)

**Comment by gnodet** [comment] 2018-04-04 09:14
Is that using the recent changes on history search ? I can't reproduce the problem, the behavior when I hit tab for me is that I end up with `history ` (with an ending space).  This is the same behavior than if I enter `history`, then go back a few chars with the left arrow, then hit tab.

**Comment by bdw429s** [comment] 2018-04-04 13:36
@gnodet Yes, that's with the latest build.  Do you have a completor that also wants to complete the same word?  When I disable my completor, the behavior doesn't happen.  It appears to be the completor and i-search fighting to complete the line at the same time.  I would guess that the completor shouldn't be fired if the user is performing an i-search?  Either that or the results of the completion should be taken into account.

**Comment by gnodet** [comment] 2018-04-04 13:50
The i-search does not react on tab.  When you hit tab, it keeps the current search as the editing buffer and push back the tab key in the stream, thereby triggering completion in the "usual" way.
It should behave exactly the same as if you enter `history`, go back to the beginning of the line, and hit `tab`.  Could you check that in this case, the completion is ok ?

**Comment by gnodet** [comment] 2018-04-04 14:35
Yes, that's what I thought.  I'm closing this issue as the i-search is working as expected.

**Closed by gnodet** 2018-04-04 14:35 UTC
