### ISSUE TITLE
Echo disabled after creating terminal

### ISSUE THREAD

**Issue by Nnidyu** [jline/jline3#55] opened 2016-12-05 17:55 UTC
This minimal example compiled with version: JLine 3.1.0 and JNA 4.2.2 disables the "echo" attribute of the terminal. 

```java
import org.jline.terminal.Terminal;
import org.jline.terminal.TerminalBuilder;
import java.io.IOException;

public class Test {
	public static void main(String... args) throws IOException {
		Terminal terminal = TerminalBuilder.builder().jna(true).build();
	}
}
```

Terminal returned from the builder is `PosixSysTerminal` with `LinuxNativePty`.

`stty -a` before running it:
```
speed 38400 baud; rows 76; columns 272; line = 0;
intr = ^C; quit = ^\; erase = ^?; kill = ^U; eof = ^D; eol = <undef>; eol2 = <undef>; swtch = <undef>; start = ^Q; stop = ^S; susp = ^Z; rprnt = ^R; werase = ^W; lnext = ^V; discard = ^O; min = 1; time = 0;
-parenb -parodd -cmspar cs8 -hupcl -cstopb cread -clocal -crtscts
-ignbrk brkint ignpar -parmrk -inpck -istrip -inlcr -igncr icrnl ixon -ixoff -iuclc -ixany imaxbel iutf8
opost -olcuc -ocrnl onlcr -onocr -onlret -ofill -ofdel nl0 cr0 tab0 bs0 vt0 ff0
isig icanon -iexten echo echoe echok -echonl -noflsh -xcase -tostop -echoprt echoctl echoke -flusho -extproc
```

After:
```
speed 38400 baud; rows 76; columns 272; line = 0;
intr = ^C; quit = ^\; erase = ^?; kill = ^U; eof = ^D; eol = <undef>; eol2 = <undef>; swtch = <undef>; start = ^Q; stop = ^S; susp = ^Z; rprnt = ^R; werase = ^W; lnext = ^V; discard = ^O; min = 1; time = 0;
-parenb -parodd -cmspar cs8 -hupcl -cstopb cread -clocal -crtscts
-ignbrk brkint ignpar -parmrk -inpck -istrip -inlcr -igncr icrnl ixon -ixoff -iuclc -ixany imaxbel iutf8
opost -olcuc -ocrnl onlcr -onocr -onlret -ofill -ofdel nl0 cr0 tab0 bs0 vt0 ff0
isig icanon -iexten -echo echoe echok -echonl -noflsh -xcase -tostop -echoprt echoctl -echoke -flusho -extproc
```

Note change to echo in the last line.

**Comment by gnodet** [comment] 2016-12-05 18:12
Could you check with the master branch ? This should be fixed already...

**Comment by Nnidyu** [comment] 2016-12-05 18:28
You are right. Sorry for the noise. I am waiting for the bugfix release then.

**Comment by gnodet** [comment] 2016-12-05 18:40
Duplicate of #52

**Closed by gnodet** 2016-12-05 18:40 UTC
