### ISSUE TITLE
jline3 crashes under cygwin: Cannot run program "infocmp"

### ISSUE THREAD

**Issue by adorokhine** [jline/jline3#150] opened 2017-07-21 08:01 UTC
When running a java program from cygwin, jline3 prints the following stack trace:

```
WARNING: Unable to create a system terminal, creating a dumb terminal (enable debug logging for more information)                                            
Jul 21, 2017 1:59:03 AM org.jline.utils.Log logr                                                                                                             
WARNING: Unable to retrieve infocmp for type cygwin                                                                                                          
java.io.IOException: Cannot run program "infocmp": CreateProcess error=2, The system cannot find the file specified                                          
        at java.lang.ProcessBuilder.start(Unknown Source)                                                                                                    
        at org.jline.utils.InfoCmp.getInfoCmp(InfoCmp.java:547)                                                                                              
        at org.jline.terminal.impl.AbstractTerminal.parseInfoCmp(AbstractTerminal.java:160)                                                                  
        at org.jline.terminal.impl.DumbTerminal.<init>(DumbTerminal.java:102)                                                                                
        at org.jline.terminal.TerminalBuilder.doBuild(TerminalBuilder.java:296)                                                                              
        at org.jline.terminal.TerminalBuilder.build(TerminalBuilder.java:172)                                                                                
        at org.jline.terminal.TerminalBuilder.terminal(TerminalBuilder.java:57)                                                                              
        at org.jline.reader.LineReaderBuilder.build(LineReaderBuilder.java:96)                                                                                                                                                                                
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified                                                             
        at java.lang.ProcessImpl.create(Native Method)                                                                                                       
        at java.lang.ProcessImpl.<init>(Unknown Source)                                                                                                      
        at java.lang.ProcessImpl.start(Unknown Source)                                                                                                       
        ... 11 more
```

**Comment by gnodet** [comment] 2017-07-21 10:21
Can you try setting your terminal to xterm-256color ?
```
export TERM=xterm-256color
```

**Comment by gnodet** [comment] 2017-09-12 08:39
Please reopen if needed.

**Comment by adorokhine** [comment] 2017-09-18 02:54
Sorry for the delay. Yes, this is still an issue.
The default value of 'TERM' is 'cygwin'.
Setting it to xterm-256color makes the crash go away, but the prompt is corrupt with all sorts of weird symbols:

"←[?1h←=/$ "

On my Ubuntu system this prompt just says:
"/$ "

(no colours).

**Comment by adorokhine** [comment] 2017-09-18 02:55
GitHub isn't allowing me to reopen the issue because I wasn't the one who closed it.

**Comment by gnodet** [comment] 2017-09-18 08:03
JLine is creating a dumb terminal, but that's not really expected.
Could you enable debug logging and find out why the correct terminal can't be created ?  Alternatively, you can set the {{org.jline.terminal.dumb=false}} system property, which should cause the builder to  throw the exception I'm interested in.

**Comment by gnodet** [comment] 2017-09-18 08:06
Also, it seems the cygwin detection might not be working.  Do you have the {{PWD}} environment variable set to something start with a slash {{/}} ?

**Comment by adorokhine** [comment] 2017-10-24 03:40
Here is the crash that happens when setting the 'dumb' system property to false:
```
Exception in thread "main" java.lang.IllegalStateException: Unable to create a system terminal                                                                                                                 
        at org.jline.terminal.TerminalBuilder.doBuild(TerminalBuilder.java:219)                                                                                                                                
        at org.jline.terminal.TerminalBuilder.build(TerminalBuilder.java:172)                                                                                                                                  
        at org.jline.terminal.TerminalBuilder.terminal(TerminalBuilder.java:57)                                                                                                                                
        at org.jline.reader.LineReaderBuilder.build(LineReaderBuilder.java:96)                                                                                                                                 
        at com.dorokhine.ufs.cmd.ShellCmd.mainLoop(ShellCmd.java:129)                                                                                                                                          
        at com.dorokhine.ufs.cmd.ShellCmd.run(ShellCmd.java:274)                                                                                                                                               
        at com.dorokhine.ufs.cmd.Main.main(Main.java:35)                                                                                                                                                       
        Suppressed: java.util.NoSuchElementException                                                                                                                                                           
                at java.util.ServiceLoader$LazyIterator.nextService(Unknown Source)                                                                                                                            
                at java.util.ServiceLoader$LazyIterator.next(Unknown Source)                                                                                                                                   
                at java.util.ServiceLoader$1.next(Unknown Source)                                                                                                                                              
                at org.jline.terminal.TerminalBuilder.load(TerminalBuilder.java:343)                                                                                                                           
                at org.jline.terminal.TerminalBuilder.doBuild(TerminalBuilder.java:243)                                                                                                                        
                ... 6 more                                                                                                                                                                                     
        Suppressed: java.util.NoSuchElementException                                                                                                                                                           
                at java.util.ServiceLoader$LazyIterator.nextService(Unknown Source)                                                                                                                            
                at java.util.ServiceLoader$LazyIterator.next(Unknown Source)                                                                                                                                   
                at java.util.ServiceLoader$1.next(Unknown Source)                                                                                                                                              
                at org.jline.terminal.TerminalBuilder.load(TerminalBuilder.java:343)                                                                                                                           
                at org.jline.terminal.TerminalBuilder.doBuild(TerminalBuilder.java:251)                                                                                                                        
                ... 6 more
```

Here's what PWD says:
```
$ echo $PWD                                                                                                                                                  
/cygdrive/c/Documents and Settings/rsync/ufs
```

**Comment by gnodet** [comment] 2017-10-24 05:53
Cygwin is detected if 
- `os.name` contains `win`
-  `PWD` env variable starts with `/`
-  `TERM` env variable is not `cygwin`

Could you set the `TERM` environment variable to `xterm` before starting your application maybe ?

**Comment by adorokhine** [comment] 2017-10-24 05:57
Setting the TERM variable to xterm just causes a corrupt-looking prompt:
`←[?1h←=/$ `

instead of:
`/$ `

Also why would cygwin be detected if the TERM variable is NOT cygwin? That seems backwards.

**Comment by gnodet** [comment] 2017-10-24 06:46
The `←[?1h←=/$` is caused by JLine setting the `keypad_xmit` mode on the terminal.  It does not seem to be supported by the terminal.  Try setting `TERM=ansi` instead.

I think the reason for not accepting `TERM=cygwin` is that in those configuration, the terminal does not support ansi sequences, but I'd have to check history if that's your case.

**Comment by adorokhine** [comment] 2017-10-24 06:53
TERM=ansi seems to work, thanks. Is it possible to get this to work out of the box somehow?

**Comment by adorokhine** [comment] 2017-10-24 06:54
Sorry, spoke to soon. The prompt looks 'ok' but it's still corrupt when doing tab completion:
```
/$ cat envtemplate                                                                                                                                           
←[36menvtemplate←[0m.doc    ←[36menvtemplate←[0m1.doc   ←[36menvtemplate←[0m2.doc←[A←[36D.doc                                                                
←[7menvtemplate.doc ←[0m←[A←[6C←[4D←[1@1
```

**Comment by gnodet** [comment] 2017-10-24 07:14
What is your environment exactly ? The cygwin terminal usually support ansi sequences correctly.
Also, what's the value of the `TERM` terminal in your case ? If the value is `cygwin`, you may understand why it's not detected as cygwin, because there's no support for ansi sequences.
In such a case, you should keep `TERM=cygwin`, but then add `jansi` or `jna` library to your classpath so that you fall back to a usual windows terminal.

**Comment by adorokhine** [comment] 2017-10-24 07:19
> What is your environment exactly?

I am on an Ubuntu workstation running Konsole as the terminal emulator. I am ssh'd to a windows box using WinSSHD. From that session I start cygwin using c:\cygwin\cygwin.bat. The prompt created by this process looks and behaves normally including colour prompts (which is the default for cygwin).

> Also, what's the value of the TERM terminal in your case?

The default value is 'cygwin'. This causes the infocmp failure. Changing it to 'xterm' causes the broken prompt, and changing it to 'ansi' causes the broken tab completes. 

> If the value is cygwin, you may understand why it's not detected as cygwin, because there's no support for ansi sequences.

I see; in that case how does the default colourized prompt get rendered with TERM=cygwin? (name of the user is green and path is brown).

> In such a case, you should keep TERM=cygwin, but then add jansi or jna library to your classpath so that you fall back to a usual windows terminal.

Is just adding these libraries to my project sufficient or do I have to hook them up with jline in some way?

Thanks!

**Comment by gnodet** [comment] 2017-10-24 07:22
You need to add `jline-terminal-jansi` + `jansi` or `jline-terminal-jna` + `jna` jars in your classpath.  You can add them all if you want, but only one will be used.
If you still see the `java.util.NoSuchElementException` you pasted above, it means your classpath is not setup correctly and can't find the required classes.

**Comment by gnodet** [comment] 2018-01-26 15:17
Closing this one, let know if it needs to be reopened.

**Closed by gnodet** 2018-01-26 15:17 UTC

**Comment by Kearny** [comment] 2019-12-16 10:55
Hello, we are encountering the same issue here. We work on Windows 10. Any clues ?

**Comment by NickRJanssen** [comment] 2020-02-12 15:31
I also have this problem, when using it within IntelliJ, 

```
feb. 12, 2020 4:30:35 P.M. org.jline.utils.Log logr
WARNING: Unable to retrieve infocmp for type dumb-color
java.io.IOException: Cannot run program "infocmp": CreateProcess error=2, The system cannot find the file specified
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
	at org.jline.utils.InfoCmp.getInfoCmp(InfoCmp.java:547)
	at org.jline.terminal.impl.AbstractTerminal.parseInfoCmp(AbstractTerminal.java:187)
	at org.jline.terminal.impl.DumbTerminal.<init>(DumbTerminal.java:88)
	at org.jline.terminal.TerminalBuilder.doBuild(TerminalBuilder.java:401)
	at org.jline.terminal.TerminalBuilder.build(TerminalBuilder.java:259)
	at org.jline.terminal.TerminalBuilder.terminal(TerminalBuilder.java:75)
	at nl.janssen.swgoh_utility.utilities.Logger.<init>(Logger.java:27)
	at nl.janssen.swgoh_utility.utilities.Logger.<clinit>(Logger.java:16)
	at nl.janssen.swgoh_utility.Application2.processArguments(Application2.java:125)
	at nl.janssen.swgoh_utility.Application2.<init>(Application2.java:41)
	at nl.janssen.swgoh_utility.Application2.main(Application2.java:146)
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
	at java.base/java.lang.ProcessImpl.create(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:478)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:154)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
	... 12 more

```

**Comment by Gandalf1783** [comment] 2020-11-16 19:51
Same for me. Any progress??

**Comment by gnodet** [comment] 2020-11-16 20:01
The `WARNING: Unable to retrieve infocmp for type dumb-color` is most probably caused by a program embedding JLine without its resources. The needed file is https://github.com/jline/jline3/blob/742b0cbade1a631c7e659619142ab6c57118e15f/terminal/src/main/resources/org/jline/utils/dumb-color.caps and should be included in the jline jar.

**Comment by lppedd** [comment] 2023-01-30 10:34
Happens trying to execute [mvnd](https://github.com/apache/maven-mvnd) from the Windows Command Prompt.

Binary used:
```
maven-mvnd-1.0.0-m1-windows-amd64.zip
```

Complete error:
```
C:\Users\edoardo.luppi>mvnd --version
Jan 30, 2023 10:07:19 AM org.jline.utils.Log logr
WARNING: Unable to retrieve infocmp for type msys
java.io.IOException: Cannot run program "infocmp": CreateProcess error=2, The system cannot find the file specified
        at java.base@17.0.5/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
        at java.base@17.0.5/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
        at org.jline.utils.InfoCmp.getInfoCmp(InfoCmp.java:547)
        at org.jline.terminal.impl.AbstractTerminal.parseInfoCmp(AbstractTerminal.java:204)
        at org.jline.terminal.impl.AbstractWindowsTerminal.<init>(AbstractWindowsTerminal.java:91)
        at org.jline.terminal.impl.jansi.win.JansiWinSysTerminal.<init>(JansiWinSysTerminal.java:100)
        at org.jline.terminal.impl.jansi.win.JansiWinSysTerminal.createTerminal(JansiWinSysTerminal.java:76)
        at org.jline.terminal.impl.jansi.JansiSupportImpl.winSysTerminal(JansiSupportImpl.java:126)
        at org.jline.terminal.TerminalBuilder.doBuild(TerminalBuilder.java:348)
        at org.jline.terminal.TerminalBuilder.build(TerminalBuilder.java:271)
        at org.mvndaemon.mvnd.common.logging.TerminalOutput.<init>(TerminalOutput.java:165)
        at org.mvndaemon.mvnd.client.DefaultClient.main(DefaultClient.java:150)
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.jni.functions.JNIFunctions$NewObjectWithObjectArrayArgFunctionPointer.invoke(JNIFunctions.java)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.jni.functions.JNIFunctions.ThrowNew(JNIFunctions.java:882)
        at java.base@17.0.5/java.lang.ProcessImpl.create(ProcessImpl.java)
        at java.base@17.0.5/java.lang.ProcessImpl.<init>(ProcessImpl.java:499)
        at java.base@17.0.5/java.lang.ProcessImpl.start(ProcessImpl.java:158)
        at java.base@17.0.5/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
        ... 11 more

mvnd 1.0.0-m1 windows-amd64 native client (7586cf2b0cdd3b57238fa70802affb7a4e6f602f)
Terminal: org.jline.terminal.impl.jansi.win.JansiWinSysTerminal
Apache Maven 4.0.0-alpha-3 (2ccf57baa5191468f9911fe85fd99672ac3bacb9)
Maven home: C:\Users\edoardo.luppi\Downloads\maven-mvnd-1.0.0-m1-windows-amd64\maven-mvnd-1.0.0-m1-windows-amd64\mvn
Java version: 17.0.4.1, vendor: Amazon.com Inc., runtime: C:\Users\edoardo.luppi\Documents\management\jvms_v2.1.1_amd64\store\corretto-17.0.4.1
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
```

cc @gnodet
