### ISSUE TITLE
editing a line after using the arrow keys to position cursor results with a useless command all while using Gitbash in VSCode

### ISSUE THREAD

**Issue by webmandman** [jline/jline3#264] opened 2018-05-07 18:31 UTC
Windows 10 x64
VSCode 1.22.2 (Shell 1.7.12, Renderer 58.0.3029.110, Node 7.9.0) 
Gitbash in VSCode
Commandbox 4.0.0 is using Jline 3.7.0

Steps to reproduce:
1. type anything in the commandbox prompt: CommandBox:dev>cat config.json
2. use left arrow key to position cursor at period, then type "uration"
3. the result is: CommandBox:dev> cat config?[@u?[@r?[@a?[@t?[@i?[@o?[@n

Once this happens shortcuts like Ctrl+a (move cursor to beginning of line) stop working too. 

![image-2018-05-07-10-49-48-735](https://user-images.githubusercontent.com/991677/39717678-dc9da11a-51e8-11e8-972c-992bdc509142.png)

**Comment by bdw429s** [comment] 2018-05-11 19:47
I was able to duplicate this too on my Windows 10 laptop.  If I open "Git Bash" via the link in my start menu I get a different terminal which works.  But if I open `C:\Program Files\Git\bin\bash.exe` (which I think VSCode uses by default) then I get the same behavior.  The name of the terminal class that's getting used for me is: `org.jline.terminal.impl.jna.win.JnaWinSysTerminal`.

**Comment by gnodet** [comment] 2018-05-29 07:21
Opening `C:\Program Files\Git\bin\bash.exe` definitely not works.  But given nothing works in this environment, I don't really consider that a problem: I can't even launch a simple bash script nor a windows batch file as expected.
To make things work, you need to launch `C:\Program Files\Git\bin\sh.exe --login -i` so that the environment is set up correctly.

**Comment by gnodet** [comment] 2018-06-11 06:42
I've tried to reproduce the problem with VSCode 1.24 + JLine 3.8.0-SNAPSHOT and it seems to work correctly for me.  Could you try again with updated versions ?

**Comment by gnodet** [comment] 2018-06-11 07:28
I'd like to release a 3.8.0 asap, so let me know if this is still a problem for you...

**Comment by gnodet** [comment] 2018-06-13 05:40
You need to use a different option for arguments:
```
"terminal.integrated.shellArgs.windows": ["--login", "-i"]
```
See https://code.visualstudio.com/docs/editor/integrated-terminal

**Comment by bdw429s** [comment] 2018-06-17 00:40
@webmandman :point_up:

**Comment by gnodet** [comment] 2018-09-03 06:48
Can I close this one ?

**Comment by bdw429s** [comment] 2018-09-04 17:14
As far as I know, this is still an issue but it looks like @webmandman stopped replying.  Let me ping him on the CFML Slack team and see if he can circle back to this.  I know there have been a number of issues reported by people trying to use the default terminal that comes with VSCode on Windows.

**Comment by webmandman** [comment] 2018-09-05 22:13
Not an issue anymore. That vscode option helped. Thank you.

**Comment by bdw429s** [comment] 2018-09-06 03:40
Thanks for replying.  I'm confused why VSCode ships with a default terminal out of the box that's so broken.  But if it's nothing JLine can help and we've documented the fix, I guess that's all we can do.  @webmandman Can you possibly document the final configuration you set here for others who come across this?

**Closed** 2019-09-05 19:26 UTC
